import { ProjectSection, ProjectTask } from "@/modules/types";

export const MASTER_CHECKLIST_SECTIONS: ProjectSection[] = [
  { id: "sec-2.1", title: "2.1 INFORMACIÓN ARQUITECTÓNICA", order: 1 },
  { id: "sec-2.2", title: "2.2 MATERIAL DE PRESENTACIÓN", order: 2 },
  { id: "sec-3.1", title: "3.1 INFORMACIÓN CONSTRUCTIVA", order: 3 },
  { id: "sec-3.2", title: "3.2 ACABADOS", order: 4 },
  { id: "sec-4", title: "4. DISEÑO ESTRUCTURAL", order: 5 },
  { id: "sec-5.1", title: "5.1 INGENIERÍA HIDRÁULICA", order: 6 },
  { id: "sec-5.2", title: "5.2 INGENIERÍA SANITARIA", order: 7 },
  { id: "sec-5.3", title: "5.3 INSTALACIÓN DE GAS", order: 8 },
  { id: "sec-5.4", title: "5.4 INGENIERÍA ELÉCTRICA", order: 9 },
  { id: "sec-6", title: "6. INSTALACIONES ESPECIALES", order: 10 },
  { id: "sec-7.1", title: "7.1 TABLAROCA", order: 11 },
];

export const MASTER_CHECKLIST_TASKS: ProjectTask[] = [
  // 2.1
  {
    id: "t-2.1.1",
    title: "2.1.1 PLANTA DE CONJUNTO",
    sectionId: "sec-2.1",
    order: 1,
    completed: false,
    favorite: false,
  },
  {
    id: "t-2.1.2",
    title: "2.1.2 PLANTAS ARQUITECTÓNICAS",
    sectionId: "sec-2.1",
    order: 2,
    completed: false,
    favorite: false,
  },
  {
    id: "t-2.1.3",
    title: "2.1.3 FACHADAS ARQUITECTÓNICAS",
    sectionId: "sec-2.1",
    order: 3,
    completed: false,
    favorite: false,
  },
  {
    id: "t-2.1.4",
    title: "2.1.4 SECCIONES LONGITUDINALES",
    sectionId: "sec-2.1",
    order: 4,
    completed: false,
    favorite: false,
  },
  {
    id: "t-2.1.5",
    title: "2.1.5 SECCIONES TRANSVERSALES",
    sectionId: "sec-2.1",
    order: 5,
    completed: false,
    favorite: false,
  },

  // 2.2
  {
    id: "t-2.2.1",
    title: "2.2.1 VISUALIZACIÓN DIGITAL (VISTA EXTERIOR E INTERIOR)",
    sectionId: "sec-2.2",
    order: 6,
    completed: false,
    favorite: false,
  },

  // 3.1
  {
    id: "t-3.1.1",
    title: "3.1.1 DETALLES DE CANCELERÍA",
    sectionId: "sec-3.1",
    order: 7,
    completed: false,
    favorite: false,
  },
  {
    id: "t-3.1.2",
    title: "3.1.2 DETALLES DE CARPINTERÍA",
    sectionId: "sec-3.1",
    order: 8,
    completed: false,
    favorite: false,
  },
  {
    id: "t-3.1.3",
    title: "3.1.3 DETALLES DE HERRERÍA",
    sectionId: "sec-3.1",
    order: 9,
    completed: false,
    favorite: false,
  },
  {
    id: "t-3.1.4",
    title: "3.1.4 DETALLES CONSTRUCTIVOS ARQUITECTÓNICOS",
    sectionId: "sec-3.1",
    order: 10,
    completed: false,
    favorite: false,
  },
  {
    id: "t-3.1.5",
    title: "3.1.5 PLANO DE ALBAÑILERIA",
    sectionId: "sec-3.1",
    order: 11,
    completed: false,
    favorite: false,
  },

  // 3.2
  {
    id: "t-3.2.1",
    title: "3.2.1 PLANO DE REFERENCIAS DE ACABADOS",
    sectionId: "sec-3.2",
    order: 12,
    completed: false,
    favorite: false,
  },
  {
    id: "t-3.2.2",
    title: "3.2.2 PLANTAS DE ACABADOS",
    sectionId: "sec-3.2",
    order: 13,
    completed: false,
    favorite: false,
  },
  {
    id: "t-3.2.3",
    title: "3.2.3 DESPIECE DE PISOS Y LAMBRINES",
    sectionId: "sec-3.2",
    order: 14,
    completed: false,
    favorite: false,
  },
  {
    id: "t-3.2.4",
    title: "3.2.4 ACCESORIOS Y EQUIPOS",
    sectionId: "sec-3.2",
    order: 15,
    completed: false,
    favorite: false,
  },
  {
    id: "t-3.2.4.1",
    title: "3.2.4.1 DETALLES ACCESORIOS Y EQUIPOS",
    sectionId: "sec-3.2",
    order: 16,
    completed: false,
    favorite: false,
  },
  {
    id: "t-3.2.5",
    title: "3.2.5 PLANO DE MÁRMOL",
    sectionId: "sec-3.2",
    order: 17,
    completed: false,
    favorite: false,
  },

  // 4
  {
    id: "t-4.1",
    title: "4.1 PLANOS DE ESPECIFICACIONES GENERALES",
    sectionId: "sec-4",
    order: 18,
    completed: false,
    favorite: false,
  },
  {
    id: "t-4.2",
    title: "4.2 PLANTA ESTRUCTURAL DE CIMENTACIÓN",
    sectionId: "sec-4",
    order: 19,
    completed: false,
    favorite: false,
  },
  {
    id: "t-4.3",
    title: "4.3 PLANTAS ESTRUCTURADAS DE LOSAS POR NIVEL",
    sectionId: "sec-4",
    order: 20,
    completed: false,
    favorite: false,
  },
  {
    id: "t-4.4",
    title: "4.4 SECCIONES ESTRUCTURALES DE REFUERZO",
    sectionId: "sec-4",
    order: 21,
    completed: false,
    favorite: false,
  },
  {
    id: "t-4.5",
    title: "4.5 SECCIONES ESQUEMÁTICAS DE NIVELES",
    sectionId: "sec-4",
    order: 22,
    completed: false,
    favorite: false,
  },
  {
    id: "t-4.6",
    title: "4.6 MEMORIA DE CÁLCULO",
    sectionId: "sec-4",
    order: 23,
    completed: false,
    favorite: false,
  },
  {
    id: "t-4.7",
    title: "4.7 MECÁNICA DE SUELOS",
    sectionId: "sec-4",
    order: 24,
    completed: false,
    favorite: false,
  },

  // 5.1
  {
    id: "t-5.1.1",
    title: "5.1.1 ACOMETIDA GENERAL, CISTERNA Y LÍNEAS GENERALES",
    sectionId: "sec-5.1",
    order: 25,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.1.2",
    title: "5.1.2 INSTALACIÓN DE LÍNEAS POR NIVEL",
    sectionId: "sec-5.1",
    order: 26,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.1.3",
    title: "5.1.3 ISOMÉTRICOS GENERALES DE INSTALACIÓN DE AGUA",
    sectionId: "sec-5.1",
    order: 27,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.1.4",
    title: "5.1.4 ESPECIFICACIONES Y DETALLES HIDRÁULICOS",
    sectionId: "sec-5.1",
    order: 28,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.1.5",
    title: "5.1.5 MEMORIA DESCRIPTIVA",
    sectionId: "sec-5.1",
    order: 29,
    completed: false,
    favorite: false,
  },

  // 5.2
  {
    id: "t-5.2.1",
    title: "5.2.1 DESCARGAS GENERALES Y DRENAJES RESIDUALES",
    sectionId: "sec-5.2",
    order: 30,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.2.2",
    title: "5.2.2 SISTEMA DE CAPTACIÓN PLUVIAL E INTERCONEXIÓN A RED",
    sectionId: "sec-5.2",
    order: 31,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.2.3",
    title: "5.2.3 PLANTAS E ISOMÉTRICOS DE INSTALACIÓN",
    sectionId: "sec-5.2",
    order: 32,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.2.4",
    title: "5.2.4 ESPECIFICACIONES Y DETALLES SANITARIOS",
    sectionId: "sec-5.2",
    order: 33,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.2.5",
    title: "5.2.5 MEMORIA DESCRIPTIVA",
    sectionId: "sec-5.2",
    order: 34,
    completed: false,
    favorite: false,
  },

  // 5.3
  {
    id: "t-5.3.1",
    title: "5.3.1 DISEÑO DE RED DE CONDUCCIÓN",
    sectionId: "sec-5.3",
    order: 35,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.3.2",
    title: "5.3.2 LÍNEAS DE ALIMENTACIÓN",
    sectionId: "sec-5.3",
    order: 36,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.3.3",
    title: "5.3.3 EQUIPOS DE CONSUMO",
    sectionId: "sec-5.3",
    order: 37,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.3.4",
    title: "5.3.4 CONJUNTO DE ABASTECIMIENTO, DISTRIBUCIÓN Y REGULACIÓN",
    sectionId: "sec-5.3",
    order: 38,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.3.5",
    title: "5.3.5 MEMORIA DESCRIPTIVA",
    sectionId: "sec-5.3",
    order: 39,
    completed: false,
    favorite: false,
  },

  // 5.4
  {
    id: "t-5.4.1",
    title: "5.4.1 ILUMINACIÓN POR NIVEL",
    sectionId: "sec-5.4",
    order: 40,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.4.2",
    title: "5.4.2 CONTACTOS POR NIVEL",
    sectionId: "sec-5.4",
    order: 41,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.4.3",
    title: "5.4.3 DIAGRAMA UNIFILAR",
    sectionId: "sec-5.4",
    order: 42,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.4.4",
    title: "5.4.4 CUADROS Y RESÚMENES DE CARGAS",
    sectionId: "sec-5.4",
    order: 43,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.4.5",
    title: "5.4.5 ESPECIFICACIONES Y DETALLES ELÉCTRICOS",
    sectionId: "sec-5.4",
    order: 44,
    completed: false,
    favorite: false,
  },
  {
    id: "t-5.4.6",
    title: "5.4.6 MEMORIA DESCRIPTIVA",
    sectionId: "sec-5.4",
    order: 45,
    completed: false,
    favorite: false,
  },

  // 6
  {
    id: "t-6.1",
    title: "6.1 DOMOTICA",
    sectionId: "sec-6",
    order: 46,
    completed: false,
    favorite: false,
  },
  {
    id: "t-6.2",
    title: "6.2 AIRE ACONDICIONADO",
    sectionId: "sec-6",
    order: 47,
    completed: false,
    favorite: false,
  },
  {
    id: "t-6.3",
    title: "6.3 VOZ Y DATOS",
    sectionId: "sec-6",
    order: 48,
    completed: false,
    favorite: false,
  },
  {
    id: "t-6.4",
    title: "6.4 SISTEMA DE RIEGO",
    sectionId: "sec-6",
    order: 49,
    completed: false,
    favorite: false,
  },
  {
    id: "t-6.5",
    title: "6.5 CCTV",
    sectionId: "sec-6",
    order: 50,
    completed: false,
    favorite: false,
  },

  // 7.1
  {
    id: "t-7.1.1",
    title: "7.1.1 PLANO DE PLAFONES",
    sectionId: "sec-7.1",
    order: 51,
    completed: false,
    favorite: false,
  },
  {
    id: "t-7.1.2",
    title: "7.1.2 PLANO MUROS DE TABLAROCA",
    sectionId: "sec-7.1",
    order: 52,
    completed: false,
    favorite: false,
  },
];
