declare module "lucide-react" {
  import * as React from "react";
  type LucideIcon = React.FC<React.SVGProps<SVGSVGElement>>;
  export const Circle: LucideIcon;
  export const CircleCheck: LucideIcon;
  export const Loader2: LucideIcon;
  export const Plus: LucideIcon;
  export const Star: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const Trash2: LucideIcon;
  export const UserPlus: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const X: LucideIcon;
  export const XIcon: LucideIcon;
  export const Check: LucideIcon;
  export const CheckIcon: LucideIcon;
  export const CircleIcon: LucideIcon;
  export const PanelLeftIcon: LucideIcon;
  export const PanelLeft: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const Filter: LucideIcon;
  export const CircleCheckBig: LucideIcon;
  export const ChevronDownIcon: LucideIcon;
  export const ChevronLeftIcon: LucideIcon;
  export const ChevronRightIcon: LucideIcon;
  export const ChevronUpIcon: LucideIcon;
  const _default: LucideIcon;
  export default _default;
}
